version: "3"

services:
  db:
    image: postgres:12-alpine
      # Where database will be mounted inside docker
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./data/db:/var/postgresql/data

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=moni
      - POSTGRES_PASSWORD=moni
      # Latest attempt to solve Could not translate host name "db" to address using Postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

    # Help solve with translating host name "db" to addreass
    # networks:
    #   - djangonetwork

  # volumes:
  #   postgres_data:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #Run using poetry first
    # command:  /bin/sh -c "start.sh"


      # Volume don't need to rerun build over and over
      # Still need to rerun the docker compose up
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    # Help solve with translating host name "db" to addreass
    # links:
    #   - db:db
    # networks:
    #   - djangonetwork
      #Added
    # environment:
    #   - DB_HOST=db


    # Help solve with translating host name "db" to addreass
# networks:
#   djangonetwork:
#     driver: bridge